# Generated by Django 4.0.6 on 2022-07-07 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0003_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('-', '-')], default='-', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course')),
            ],
            options={
                'ordering': ['second_name'],
                'unique_together': {('first_name', 'second_name', 'date_of_birth', 'email')},
            },
        ),
    ]
